name: Pull request
on:
  pull_request:
    branches:
      - main
jobs:
  vet:
    name: Vet
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-vet
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Mise
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: go mod download
      - name: Lint
        run: go vet ./...
      - name: Run tests
        run: go test -v ./... -bench=. -benchmem
